package web;

import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import domain.User;

@WebServlet("/registration")
public class Registration extends HttpServlet {
	private static final long serialVersionUID = 1L;
       
    public Registration() {
        super();
    }

	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		String login = request.getParameter("login");
		String password = request.getParameter("password");
		String type = request.getParameter("type");
	
		User user = new User(login, password, type);
		
		registerUser(user, response);
	}
	
	private void registerUser(User user, HttpServletResponse response) throws IOException {
		String url = "jdbc:hsqldb:hsql://localhost/workdb";

		try {
			Connection connection = DriverManager.getConnection(url);
			
			String createUserTableSql = 
				"CREATE TABLE IF NOT EXISTS users("
				+ "id int GENERATED BY DEFAULT AS IDENTITY,"
				+ "login VARCHAR(20),"
				+ "password VARCHAR(20),"
				+ "type VARCHAR(20)"
				+ ")";

			Statement createTable = connection.createStatement();
			createTable.executeUpdate(createUserTableSql);
			
			String registerUserSql = 
				"INSERT INTO users(login, password, type) VALUES ('"
				+ user.getLogin() + "', '"
				+ user.getPassword() + "', '"
				+ user.getType() + "'"
				+ ")";
			
			Statement registerUser = connection.createStatement();
			int i = registerUser.executeUpdate(registerUserSql);
			
			if (i > 0) {
				response.sendRedirect("/");
			}
		} catch (SQLException e) {
			e.printStackTrace();
		}
	}
}
